### ISSUE TITLE
"The type or namespace name 'PJS' could not be found" in Layout.cshtml

### ISSUE THREAD

**Issue by Thierry-S** [psenechal/PJS.Bootstrap#12]
Fresh install of Orchard 1.10. Download PJS Bootstrap from Theme page. It's fine. Set as current.
Browse to the home page, you get an error:
```
Compiler Error Message: CS0246: The type or namespace name 'PJS' could not be found (are you missing a using directive or an assembly reference?)

Source Error:

Line 1:  @using Orchard.ContentManagement;
Line 2:  @using PJS.Bootstrap.Models;
Line 3:  @functions {

Source File: c:\inetpub\orchard\Themes\PJS.Bootstrap\Views\Layout.cshtml    Line: 2 
```

I've tried playing with the web.config and changing the targetFramework="4.5.1" and targetFramework="4.5.2" as there's a mismatch between Orchard and the theme, but that's not fixed anything.

Any ideas?

**Comment by donaldboulton** [comment]
What version of Orchard are you using? Maybe Jetbrains Annotations is missing, view the updated code changes.

**Comment by Thierry-S** [comment]
Hi. Version was in original message: 1.10.
What do you mean by: "view the updated code changes" ??

**Comment by donaldboulton** [comment]
The line  @using PJS.Bootstrap.Models; allows you to do theme settings in admin. 
I Downloaded the code in this repository, code tab, as it has been updated for 1.10.
But the same issue, "so its not fixed".
And to get it to work is a pain but below is how you do it.
See bottom of this post for fixed files you can download. Read below and she what changed and you will lose bootstrap Theme-Settings in admin
What I did was go to Theme Bootstrap and set the styles in settings  and removed anything in View files with if statement, as below
Remove
`<html lang="@WorkContext.CurrentCulture" class="static @Html.ClassForPage() @(settings.UseFluidLayout ? "fluid-layout" : "boxed-layout") @(settings.UseFixedNav ? "fixed-nav" : "floating-nav") @(settings.UseStickyFooter ? "sticky-footer" : string.Empty) @(cultureInfo.TextInfo.IsRightToLeft ? "rtl" : string.Empty)">
`
Add it back with the styles as
`<html itemscope="itemscope" itemtype="http://schema.org/WebSite" lang="@WorkContext.CurrentCulture" class="static detail-page contents fluid-layout fixed-nav sticky-footer" xmlns="http://www.w3.org/1999/xhtml">`
I was having the same issue so remove  @using PJS.Bootstrap.Models; and set your styles manually.
Remove lines  from Layout.cshtml and Document.cshtml and Resources.cshtml
`@using PJS.Bootstrap.Models; `
and
`var settings = WorkContext.CurrentSite.As<BootstrapThemeSettingsPart>();`
 and in Resources remove.
`Style.Include("site-" + settings.Swatch + ".min.css");
    if (cultureInfo.TextInfo.IsRightToLeft) {
        Style.Include("site-rtl.min.css");
    }`
then add
Could not get it to register the stylesheet had to add external .css
If you use aws s3 you could upload your stylesheet there and use it otherwise it does not work.
If you can add a external stylesheet add it to Document.cshtml right above the closing </head> tag
`<link rel="stylesheet" type="text/css" href="//YOUR LINK" /> `
`</head>`
Remove
 `if (settings.UseHoverMenus) {
        Script.Require("HoverDropdown");
   }`
then add it as if you want hover menus if not just delete and do not add below
`Script.Include("hover-dropdown.js")`

in layouts remove
`<div class="navbar @(settings.UseInverseNav ? "navbar-inverse" : "navbar-default") @(settings.UseFixedNav ? "navbar-fixed-top" : `string.Empty)">`
and add it with the styles you like as in mine
`<div class="navbar navbar-default navbar-fixed-top">` 
Then remove in Layout
` @if (settings.UseNavSearch)` 
                   `  {` 
                       `  @Display.NavSearch()` 
                   `  }` 
and add it back with
` @Display.NavSearch()` 
or not if you want your search somewhere else.
And then I get it to work with 1.10 latest code and built and published in Visual Studio. not the Orchard.web.zip file. Even though it should work.
I zipped up the changes you can download it here.
[PJS.Fix.zip](https://s3.amazonaws.com/mansbooks_images/zip/Pjs.Fix.zip)

**Comment by Thierry-S** [comment]
Thanks for this. Loosing bootstrap Theme-Settings in admin is a shame!
I've downloaded orchard and pjs.bootstrap code and running in VS.

1) to get rid of the first error "The type or namespace name 'PJS' could not be found" I simply added a reference to PJS.Bootstrap project in the Orchard.Web project. This is bad and only a temporary thing to progress a bit.

2) So now I see this line in layout.cshtml that returns null:
var settings = WorkContext.CurrentSite.As<BootstrapThemeSettingsPart>();

and this is down to this code, which obviously returns null:
![image](https://cloud.githubusercontent.com/assets/13853345/14498241/9044b776-0191-11e6-974a-b8d452de0afb.png)

I suppose one of those 10 element is supposed to be of type BootstrapThemeSettingsPart. Element Id 5 looks like the right one: {Orchard.Themes.Models.ThemeSiteSettingsPart}. If I expand it, it has a member ThemeName="PJS.Bootstrap-master-b7bb696". If I explore inside this in the debugger, I can't see anything for a Type called BootstrapThemeSettingsPart. It always seems related to ThemeSiteSettingsPart. So does it mean somewhere in Orchard it's not using the correct Theme part? Is it an Orchard bug or a PJSBootstrap bug, some config missing somewhere? I've read http://docs.orchardproject.net/Documentation/Adding-custom-settings and http://docs.orchardproject.net/Documentation/add-custom-settings-to-your-theme and it seems that PJS.Bootstrap is following exactly the examples.
I'm new to Orchard, so not sure I can find out more than that.

Although... maybe this is a red herring. Maybe the real issue is why the "using PJS.Bootstrap.Models;" statement failing (point 1 above)? Maybe the underlying reason for that is also why the SettingsPart is not picked up correctly in my point 2 above. I'm going to explore this a bit.

**Comment by donaldboulton** [comment]
Be nice to know how to do it right.
I pull all my static assets from a cdn so its not really a issue for me I always removed handlers models and gravatar I do not use them.
This Orchard Fork might give you some ideas. This new Admin theme in the fork below I am making into a front end theme = very cool.
[sfmskywalker/Orchard forked from OrchardCMS/Orchard](https://github.com/sfmskywalker/Orchard)

**Comment by donaldboulton** [comment]
Check out [IDeliverable.ThemeSettings](https://github.com/IDeliverable/IDeliverable.ThemeSettings)
Working on admin theme for the next few days. I will be adding this soon to back end and front end, it looks up to date and should solve the pjs.bootstrap settings issues.
Also check out the second version of this theme with theme settings on the front end at:
[3.2.0.1](http://orchardgalleryfe.cloudapp.net/List/Themes/Orchard.Theme.PJS.Bootstrap/3.2.0.1)

**Comment by Thierry-S** [comment]
I've gone a different route.

To fix the `The type or namespace name 'PJS' could not be found` in Layout.cshtml for `using PJS.Bootstrap.Models;` I've simply copied the PJS.Bootstrap.dll into the bin folder of the orchard web folder.
Before doing that, I learned about the orchard dynamic compiler. In the file DefaultExtensionCompiler.cs in Orchard.Framework project, I ended up in the Exception catch `throw new OrchardCoreException(T("Error compiling module ...` and it said it couldn't find `System.Data.DataSetExtensions`. This is referenced by PJS.Bootstrap, but somehow Orchard doesn't find it. Maybe that's the root of the problem for error `The type or namespace name 'PJS' could not be found`.
Anyway, for production, I will disable dynamic compilation, so I'm happy copying the dll. But it should be fixed.

Then I got another problem. All the files under Scripts and Styles subfolders returned a 500 server error. Also in the admin section under settings/Theme Bootstrap admin page, the images under Content subfolder also had 500 server errors.
As described in my post here: https://github.com/OrchardCMS/Orchard/issues/5675 I had to add a `<remove name="StaticFile"/>` for all `<add name="StaticFile"...` in all child web.config. Why do I have to do this? other themes like TheThemeMachine have the same `<add name="StaticFile"...` in child web.config, and don't have this issue. There must be something somewhere not set properly either in the Bootstrap theme or in Orchard.
Let me know if you find out what!

I finally have a Boostrap-looking theme working in orchard :-)

**Comment by donaldboulton** [comment]
Fixed it NOW it works with Orchard 1.9.3 or 1.10 or dev build from today. 
Fully tested Zip file with fixed PJS.Bootstrap for 1.10 adding JetBrains.Annotations also you should add it to Orchard with package manager.
ZIp file for [PJS.Bootstrap](https://s3.amazonaws.com/mansbooks_images/zip/PJS.Bootstrap.zip)

Read below as this is how you fix old modules also.

Add PJS.Bootstrap as a new project in VS. 1.0 or dev and look at the references. 
Core and Framework have old references
MVC is version 4.0.0.0.
Remove then add correct ones. For MVC just remove MVC reference then use package manager to add MVC 5.3.0 and it will add MVC and the other updated  correct assemblies for PJS.Bootstrap not Orchard
PJS.Bootstrap.csproj is outdated
Change 
`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`
To new Tools Version
`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`
add 
`<ItemGroup>
    <Content Include="packages.config" />
  </ItemGroup>`
then copy packages.config from any module to root of PJS.Bootstrap.
`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net451" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net451" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net451" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net451" />
  <package id="Newtonsoft.Json" version="7.0.1" targetFramework="net451" />
</packages>`

Change root web.config from
`<remove assembly="System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />`

to
`<add assembly="System.Web.Entity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />`
      `<add assembly="System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />`
Update PJS web.config to 4.5.2 and MVC 5.2.3
Then use package Manager
Add JetBrains.Annotations
After installation you should have in root package file.
<package id="JetBrains.Annotations" version="10.1.4" targetFramework="net452" />

The above is how you would fix old modules also
References to core and framework and MVC. Then adding JetBrains.Annotations for some of the modules, as they were built with resharper and you get  [UsedImplicitly] and a dead reference to
`using JetBrains.Annotations;`
Mostly Themes and Old Modules were built having referenced
`<remove assembly="System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />`
which need
`<add assembly="System.Web.Entity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089" />`

**Comment by Thierry-S** [comment]
Hmmm, it looks like they do NOT want Jetbrains.Annotations. They were removed previously:
https://github.com/psenechal/PJS.Bootstrap/commit/5c17a7bb746250a14a63bd33a22f07f7b7e90d3e

**Comment by edikaufmann** [comment]
I've seen that this issue opened on March.
end of August I still have the very same issue!
I downloaded a fresh 1.10.1; only installed PJS.Bootstrap and get same error: see also attached file.
what am I doing wrong?
thanks for your time and hints
ed

[PJS.txt](https://github.com/psenechal/PJS.Bootstrap/files/448058/PJS.txt)

**Comment by edikaufmann** [comment]
just realise:
- msg from aug 31 : I used .nupkg
- with .zip it works
... no idea
